### ISSUE TITLE
Non-functional requirment 

### ISSUE THREAD

**Issue by shmouses** [LeilaMousapour/Brain-Computer-Interface-#14] opened 2020-10-27 00:32 UTC
Isn't your R7 identical to your R1? I think R7 can be considered a functional requirement. 

![image](https://user-images.githubusercontent.com/49411064/97242163-801a3a80-17c9-11eb-9bfc-b47312e5e872.png)

![image](https://user-images.githubusercontent.com/49411064/97242144-6a0c7a00-17c9-11eb-8e24-e8cfe04d1990.png)

**Comment by smiths** [comment] 2020-10-27 03:34
@shmouses, the screen shot in the issue is very much appreciated.  I can understand your issue just by reading it, without a need to consult another resources.

@shmouses, I agree with your assessment.  A requirements to check the input validity is a functional requirement, and the requirement should only be given once.

@LeilaMousapour, please include the commit has that addresses this issue in the commit message for closing the issue.

**Comment by LeilaMousapour** [comment] 2020-11-13 18:29
Addressed in commit #c047177

**Comment by LeilaMousapour** [comment] 2020-11-13 18:30
Fixed #c047177

**Closed as completed by LeilaMousapour** 2020-11-13 18:30 UTC
